version: '3'
services:
    gym-duckietown-server:
        build: ./docker/server/
        image: duckietown/gym-duckietown-server
        networks:
        - gym-duckietown-net
        environment:
        - DISPLAY=:0
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        ports:
        - "8902:8902"
        - "5558:5558"
    gym-duckietown-agent:
        build: ./
        image: duckietown/gym-duckietown-agent
        depends_on:
        - "gym-duckietown-server"
        environment:
        - DUCKIETOWN_SERVER=gym-duckietown-server
        networks:
        - gym-duckietown-net

networks:
  gym-duckietown-net:


